spring.application.name=SirenAlert24
spring.datasource.url=jdbc:mysql://localhost:3306/sirenalert
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.data.jdbc.dialect=mysql
spring.jpa.show-sql=true
